server:
  port: 8081
support:
  redishost: 111.231.109.105
  redisport: 6379
  redispassword:
spring:
#  datasource:
#    url: jdbc:mysql://111.231.109.105/test?useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  redis:          # REDIS (RedisProperties)
#    database: 0            # Redis数据库索引（默认为0）
#    host: localhost        # Redis服务器地址
#    port: 6379             # Redis服务器连接端口
#    password:             # Redis服务器连接密码（默认为空）
#    jedis:
#      pool:
#        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8       # 连接池中的最大空闲连接
#        min-idle: 0       # 连接池中的最小空闲连接
#    timeout: 5000ms          # 连接超时时间（毫秒）
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      expiry-timeout:
  kafka:
    bootstrap-servers: 111.231.109.105:9092
    producer:
      acks: all
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#######################################################################################################
#     此处配置debug=true，该属性置为true的时候，                                                         #
# 核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，但是你自己应用的日志并不会输出为DEBUG级别。  #
#######################################################################################################
#debug: true
logging:
#  file: mylog.log
#  level:
#    com.*: info
  config: classpath:logback/logback-dev.xml
###########################
##########多数据源##########
###########################
#master 数据源
master:
  datasource:
    url: jdbc:mysql://111.231.109.105:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
#cluster 数据源
cluster:
  datasource:
    url: jdbc:mysql://111.231.109.105:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver