server:
  port: 8081
  servlet:
    context-path: /springbootdev
com:
  hh:
    jn:
      blog:
        name: 姜宁宁
        title: study spring boot
        des: ${com.hh.jn.blog.name}正在${com.hh.jn.blog.title}
spring:
  profiles:
    active: dev
  thymeleaf:       # Thymeleaf 相关配置
    cache: false          # 开发环境设置为fasle， 生产环境设置为true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML
mybatis:
  type-aliases-package: com.hh.springbootdev.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.hh.springbootdev.handler
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-${spring.profiles.active}.xml
