com:
  hh:
    jn:
      blog:
        name: 姜宁宁
        title: study spring boot
        des: ${com.hh.jn.blog.name}正在${com.hh.jn.blog.title}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  thymeleaf:  # Thymeleaf 相关配置
    cache: false #开发环境设置为fasle， 生产环境设置为true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
#######################################################################################################
#     此处配置debug=true，该属性置为true的时候，                                                         #
# 核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，但是你自己应用的日志并不会输出为DEBUG级别。  #
#######################################################################################################
#debug: true
logging:
#  file: mylog.log
#  level:
#    com.*: info
  config: src/main/resources/logback/logback-dev.xml
mybatis:
  type-aliases-package: com.hh.springbootdev.entity
  mapper-locations: classpath:mapper/*.xml